In [1]:
import numpy as np

In [2]:
rand_sensor_data = np.random.rand(1000)

In [3]:
rand_sensor_data[:10]

array([0.71945933, 0.92382987, 0.50842847, 0.66793143, 0.39826118,
       0.45897921, 0.54141922, 0.24144606, 0.60372758, 0.01678038])

In [4]:
mean = np.mean(rand_sensor_data)

In [5]:
print(mean)

0.5016410365935217


In [7]:
std_dev = np.std(rand_sensor_data)

In [8]:
std_dev

0.2877026131373635

In [9]:
var = np.var(rand_sensor_data)

In [10]:
print(var)

0.08277279360606746


In [11]:
filtered_sensor_data = rand_sensor_data[rand_sensor_data <= 0.5]

In [12]:
filtered_sensor_data

array([3.98261183e-01, 4.58979211e-01, 2.41446063e-01, 1.67803821e-02,
       2.92176350e-01, 2.25238138e-01, 1.32777107e-01, 1.99266673e-01,
       1.15284892e-01, 4.27923952e-01, 3.89681936e-01, 1.07984872e-01,
       2.50638784e-01, 1.06871964e-01, 1.90492820e-01, 2.98430020e-01,
       4.16656833e-01, 6.78149787e-02, 3.16385520e-02, 2.78803640e-01,
       2.31052196e-01, 7.20525888e-02, 3.22927651e-01, 5.99133712e-02,
       9.72765371e-03, 7.12667084e-02, 4.99995383e-01, 1.37935146e-01,
       1.86941830e-01, 3.71707147e-01, 9.79788906e-02, 1.87137777e-01,
       1.01464415e-01, 4.93438828e-01, 4.78081491e-01, 2.67948814e-01,
       2.81710631e-01, 2.28713041e-01, 2.63560672e-02, 2.73976116e-01,
       3.44419107e-01, 4.89809177e-01, 9.48575192e-02, 4.16100831e-01,
       1.58004952e-01, 2.08307504e-01, 1.70818788e-01, 3.07958343e-02,
       4.43847473e-01, 3.15632068e-01, 1.15206725e-01, 3.19296852e-01,
       7.73715329e-02, 9.70897735e-02, 9.21242148e-02, 4.08346480e-01,
      

In [13]:
sensor_data = np.array([[10, 23], [11, 24], [12, 26], [13, 25], [14, 28]])

In [14]:
vibration_threshold = 12

In [15]:
failures = np.where(sensor_data[:, 0] > vibration_threshold, 1, 0)

In [16]:
failures

array([0, 0, 0, 1, 1])

In [ ]:
n